sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t enkhtushig/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true enkhtushig/react-test npm test

after_success:
  - docker build -t enkhtushig/multi-client ./client
  - docker build -t enkhtushig/multi-nginx ./nginx
  - docker build -t enkhtushig/multi-server ./server
  - docker build -t enkhtushig/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push enkhtushig/multi-client
  - docker push enkhtushig/multi-nginx
  - docker push enkhtushig/multi-server
  - docker push enkhtushig/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'us-west-1'
    app: 'multi-docker'
    env: 'Multi-docker-env'
    bucket_name: 'elasticbeanstalk-us-west-1-141095122109'
    bucket_path: 'docker-multi'
    on:
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
